import { useState } from 'react';
import { FileText, Download, Image, FileJson, Printer } from 'lucide-react';
import GlassCard from '../common/GlassCard';
import SectionTitle from '../common/SectionTitle';
import RunActionBar from '../common/RunActionBar';
import { useT } from '../../i18n';
import type { TranslationKey } from '../../i18n';

const templateKeys: { value: string; labelKey: TranslationKey }[] = [
  { value: 'Full Evaluation Report', labelKey: 'reports.fullEvalReport' },
  { value: 'Training Summary', labelKey: 'reports.trainingSummary' },
  { value: 'Comparison Brief', labelKey: 'reports.comparisonBrief' },
  { value: 'Risk Analysis', labelKey: 'reports.riskAnalysis' },
];

const sectionOptions: { key: string; labelKey: TranslationKey }[] = [
  { key: 'overview', labelKey: 'reports.overviewConfig' },
  { key: 'metrics', labelKey: 'reports.metricsSummary' },
  { key: 'charts', labelKey: 'reports.performanceCharts' },
  { key: 'terrain', labelKey: 'reports.terrainAnalysis' },
  { key: 'risk', labelKey: 'reports.riskBreakdown' },
  { key: 'comparison', labelKey: 'reports.baselineComparison' },
  { key: 'conclusion', labelKey: 'reports.conclusion' },
];

interface GeneratedReport {
  id: string;
  name: string;
  template: string;
  date: string;
  size: string;
}

const demoReports: GeneratedReport[] = [
  { id: 'rpt_001', name: 'Hongik_eval_full_20260315.pdf', template: 'Full Evaluation Report', date: '2026-03-15 18:30', size: '2.4 MB' },
  { id: 'rpt_002', name: 'Training_summary_20260314.pdf', template: 'Training Summary', date: '2026-03-14 23:45', size: '1.1 MB' },
  { id: 'rpt_003', name: 'Comparison_Hongik_vs_Inje.pdf', template: 'Comparison Brief', date: '2026-03-13 14:20', size: '0.8 MB' },
];

const markdownPreview = `# Evaluation Report — Hongik_48km

## 1. Overview

| Parameter | Value |
|-----------|-------|
| **Run ID** | 04_training__Hongik_48km__a1b2c3 |
| **Algorithm** | MaskablePPO |
| **Terrain** | Hongik_48km |
| **Training Steps** | 300,000 |
| **Checkpoint** | best_model.zip (Step 280K) |

## 2. Metrics Summary

| Metric | RL (Ours) | A* | Random | FSM |
|--------|-----------|-----|--------|-----|
| Success Rate | **71%** | 55% | 8% | 42% |
| Avg Reward | **89.3** | 52.0 | -42.1 | 38.5 |
| Integrated Risk | **0.18** | 0.25 | 0.52 | 0.31 |
| Path Length (m) | 24,500 | 22,000 | 31,000 | 26,000 |

## 3. Performance Charts

*[Success Rate Comparison — Bar Chart]*

*[Risk Distribution — Box Plot]*

*[Reward Curve — Line Chart]*

## 4. Terrain Analysis

The Hongik_48km terrain presents moderate elevation variance (σ=145m) with significant slope gradients in the northeast quadrant. The hazard map indicates three primary threat corridors aligned with ridge lines.

## 5. Risk Breakdown

- **Low Risk Zones**: 62% of path segments
- **Medium Risk Zones**: 28% of path segments
- **High Risk Zones**: 10% of path segments
- **Peak Risk Event**: Step 48, Risk = 0.38 (popup observation phase)

## 6. Conclusion

The MaskablePPO agent achieves a **71% success rate** on the Hongik_48km terrain, outperforming all baselines. Risk management remains effective with an integrated risk of 0.18, well below the 0.30 threshold.

---
*Generated by LAH Studio · 2026-03-15 18:30*
`;

export default function Reports() {
  const [selectedRun, setSelectedRun] = useState('04_training__Hongik_48km__a1b2c3');
  const [template, setTemplate] = useState(templateKeys[0].value);
  const [sections, setSections] = useState<Record<string, boolean>>(
    Object.fromEntries(sectionOptions.map((s) => [s.key, true]))
  );
  const [includePNG, setIncludePNG] = useState(true);
  const [status, setStatus] = useState('idle');
  const t = useT();

  const toggleSection = (key: string) =>
    setSections((prev) => ({ ...prev, [key]: !prev[key] }));

  const exportButtons: { labelKey: TranslationKey; icon: typeof FileText; color: string }[] = [
    { labelKey: 'reports.exportPDF', icon: FileText, color: 'text-red-500' },
    { labelKey: 'reports.exportMarkdown', icon: FileText, color: 'text-gray-600' },
    { labelKey: 'reports.exportJSON', icon: FileJson, color: 'text-blue-500' },
    { labelKey: 'reports.exportPNGBundle', icon: Image, color: 'text-green-500' },
  ];

  return (
    <div className="grid grid-cols-12 gap-6 h-full">
      {/* LEFT - Config */}
      <div className="col-span-3 space-y-4 overflow-y-auto">
        <GlassCard>
          <SectionTitle title={t('reports.configuration')} />
          <div className="space-y-3">
            <div>
              <label className="text-xs text-gray-500 font-medium">{t('reports.run')}</label>
              <select
                value={selectedRun}
                onChange={(e) => setSelectedRun(e.target.value)}
                className="w-full mt-1 px-3 py-2 text-sm bg-white/60 border border-gray-200/60 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/30"
              >
                <option value="04_training__Hongik_48km__a1b2c3">Training Run (Hongik)</option>
                <option value="04_training__Inje_48km__xyz">Training Run (Inje)</option>
              </select>
            </div>
            <div>
              <label className="text-xs text-gray-500 font-medium">{t('reports.template')}</label>
              <select
                value={template}
                onChange={(e) => setTemplate(e.target.value)}
                className="w-full mt-1 px-3 py-2 text-sm bg-white/60 border border-gray-200/60 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/30"
              >
                {templateKeys.map((tk) => (
                  <option key={tk.value} value={tk.value}>{t(tk.labelKey)}</option>
                ))}
              </select>
            </div>
          </div>
        </GlassCard>

        <GlassCard>
          <SectionTitle title={t('reports.sections')} />
          <div className="space-y-1.5">
            {sectionOptions.map((s) => (
              <label key={s.key} className="flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-100/60 cursor-pointer text-sm">
                <input
                  type="checkbox"
                  checked={sections[s.key]}
                  onChange={() => toggleSection(s.key)}
                  className="rounded border-gray-300 text-blue-500"
                />
                <span className="text-gray-700">{t(s.labelKey)}</span>
              </label>
            ))}
          </div>
          <label className="flex items-center gap-2 mt-3 px-2 py-1.5 rounded-lg hover:bg-gray-100/60 cursor-pointer text-sm border-t border-gray-200/50 pt-3">
            <input
              type="checkbox"
              checked={includePNG}
              onChange={() => setIncludePNG(!includePNG)}
              className="rounded border-gray-300 text-blue-500"
            />
            <Image size={14} className="text-gray-400" />
            <span className="text-gray-700">{t('reports.includeChartPNG')}</span>
          </label>
        </GlassCard>

        <RunActionBar
          status={status}
          onRun={() => { setStatus('running'); setTimeout(() => setStatus('completed'), 2000); }}
          onStop={() => setStatus('stopped')}
        />
      </div>

      {/* CENTER - Preview */}
      <div className="col-span-6 space-y-4 overflow-y-auto">
        <GlassCard>
          <div className="flex items-center justify-between mb-4">
            <SectionTitle title={t('reports.preview')} className="mb-0" />
            <div className="flex items-center gap-2">
              <button className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200">
                <Printer size={13} /> {t('common.print')}
              </button>
            </div>
          </div>
          <div className="bg-white rounded-xl border border-gray-200/60 p-6 max-h-[600px] overflow-y-auto">
            <div className="prose prose-sm max-w-none">
              {markdownPreview.split('\n').map((line, i) => {
                if (line.startsWith('# '))
                  return <h1 key={i} className="text-xl font-bold text-gray-900 mb-4 border-b pb-2">{line.slice(2)}</h1>;
                if (line.startsWith('## '))
                  return <h2 key={i} className="text-lg font-semibold text-gray-800 mt-6 mb-3">{line.slice(3)}</h2>;
                if (line.startsWith('| '))
                  return (
                    <div key={i} className="font-mono text-xs text-gray-600 leading-relaxed">
                      {line}
                    </div>
                  );
                if (line.startsWith('- '))
                  return <div key={i} className="text-sm text-gray-700 ml-4 mb-1">• {line.slice(2)}</div>;
                if (line.startsWith('*['))
                  return (
                    <div key={i} className="my-3 p-8 bg-gray-50 rounded-lg border border-dashed border-gray-300 text-center text-xs text-gray-400 italic">
                      {line.replace(/\*/g, '')}
                    </div>
                  );
                if (line.startsWith('---'))
                  return <hr key={i} className="my-4 border-gray-200" />;
                if (line.startsWith('*'))
                  return <p key={i} className="text-xs text-gray-400 italic">{line.replace(/\*/g, '')}</p>;
                if (line.trim() === '') return <div key={i} className="h-2" />;
                return <p key={i} className="text-sm text-gray-700 leading-relaxed mb-2">{line}</p>;
              })}
            </div>
          </div>
        </GlassCard>
      </div>

      {/* RIGHT - Export & History */}
      <div className="col-span-3 space-y-4 overflow-y-auto">
        <GlassCard>
          <SectionTitle title={t('common.export')} />
          <div className="space-y-2">
            {exportButtons.map((opt) => (
              <button
                key={opt.labelKey}
                className="w-full flex items-center gap-3 px-3 py-2.5 text-sm text-gray-700 bg-white/60 border border-gray-200/60 rounded-xl hover:bg-gray-100/60 transition-colors"
              >
                <opt.icon size={16} className={opt.color} />
                {t(opt.labelKey)}
                <Download size={13} className="ml-auto text-gray-400" />
              </button>
            ))}
          </div>
        </GlassCard>

        <GlassCard>
          <SectionTitle title={t('reports.generatedReports')} />
          <div className="space-y-2">
            {demoReports.map((r) => (
              <div
                key={r.id}
                className="flex items-start gap-3 px-3 py-2.5 bg-white/40 border border-gray-200/40 rounded-xl hover:bg-white/60 cursor-pointer transition-colors"
              >
                <FileText size={16} className="text-red-400 mt-0.5 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <div className="text-xs font-medium text-gray-700 truncate">{r.name}</div>
                  <div className="text-[10px] text-gray-400 mt-0.5">{r.template}</div>
                  <div className="flex items-center gap-2 text-[10px] text-gray-400 mt-0.5">
                    <span>{r.date}</span>
                    <span>·</span>
                    <span>{r.size}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </GlassCard>
      </div>
    </div>
  );
}
